### ISSUE TITLE
Dataset split configuration of HOI4D

### ISSUE THREAD

**Issue by dqj5182** [janehwu/mcc-ho#4]
May I ask how you split HOI4D dataset in training / validation / test set? In the paper it says that "142 training sequences, 6
validation sequences, and 12 test sequences consistent with DiffHOI". However, DiffHOI did not seem to mention such dataset split neither in their paper or code.

If possible, may I ask for exact names of sequences of "142 training sequences, 6 validation sequences, and 12 test sequences consistent with DiffHOI"?

**Comment by janehwu** [comment]
Hi! DiffHOI posted the 12 test sequences on their website, so I reverse engineered the sequence names: https://judyye.github.io/diffhoi-www/vid_main/vis.html

In any case, here are the val and test sequences (training is the remainder):
[hoi4d_val_sequences.txt](https://github.com/janehwu/mcc-ho/files/15490868/hoi4d_val_sequences.txt)
[hoi4d_test_sequences.txt](https://github.com/janehwu/mcc-ho/files/15490866/hoi4d_test_sequences.txt)
