### ISSUE TITLE
implementation of Demo (without HaMeR)

### ISSUE THREAD

**Issue by YangChangHee** [janehwu/mcc-ho#5]
Hello, thank you for creating such a great project!

I’ve completed the environment setup and ran the Demo (without HaMeR). After the log below appeared, I checked the obj and output.html files. The point cloud seems to be generated correctly, but the mesh surface information looks incorrect. Could you please let me know if I might have made any mistakes during the process?
```
point mccho_best_checkpoint.pth 
Resume checkpoint mccho_best_checkpoint.pth
<All keys matched successfully>
/root/.pyenv/versions/MCC-HO/lib/python3.9/site-packages/pytorch3d-0.7.8-py3.9-linux-x86_64.egg/pytorch3d/io/obj_io.py:547: UserWarning: No mtl file provided
  warnings.warn("No mtl file provided")
Camera intrinsics: 3.5556 3.5556 0.0 -0.7778
Depth: torch.Size([720, 1280])
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 108/108 [00:21<00:00,  4.96it/s]
Unnormalizing predicted points
Writing obj to: demo/output_0.1.obj
Unnormalizing predicted hand points
Unnormalizing predicted obj points
```
![image](https://github.com/user-attachments/assets/d883fdd6-494a-4819-bffc-4405482f59f6)
![image](https://github.com/user-attachments/assets/6b8fed05-24bc-4000-b3cf-fdff5ff50519)

best regards,

**Comment by janehwu** [comment]
Hi, thanks for your interest!

"the mesh surface information" -> MCC-HO only outputs the object as a point cloud. Specifically, the model decoder outputs occupancy for any x,y,z location in 3D space, so there is no surface reconstruction (e.g. no output mesh).

I'm unsure how you are generating triangles in your visualization, but this would not be anything related to our demo.

Hope this helps!
